#cloud-config
---
package_update: true
packages:
  - iotop

groups:
  - sysadmin
  - oinstall

users:
  - name: admin
    gecos: "Usuario administrador de S.O"
    primary_group: sysadmin
    lock_passwd: false
    passwd: '6$Dn2Z1eIqXbAOUM1o$8JzSBlrEsv9orWTibXrUg9EDNRxVY2MiWT9zhXEUKN2WxMylKLpLs0kRuGb.pmcApb6qggOaIE3MzlcWbVyGX1'
    sudo: ["ALL=(ALL) ALL"]
    shell: /bin/bash

  - name: grid
    gecos: "Usuario DBA"
    primary_group: oinstall
    lock_passwd: false
    passwd: '6$Dn2Z1eIqXbAOUM1o$8JzSBlrEsv9orWTibXrUg9EDNRxVY2MiWT9zhXEUKN2WxMylKLpLs0kRuGb.pmcApb6qggOaIE3MzlcWbVyGX1'

write_files:
  - content: |
      ola khe ase
    path: /holi.txt
    owner: root
    permissions: '0600'

  - content: |
      export TERM=vt100
    path: /etc/profile
    append: true
...
